name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Execute Test Suite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute tests
        run: |
          cd src && python -m pytest ../tests/ -v

  model_train_quant:
    runs-on: ubuntu-latest
    name: Train and Quantize Model
    needs: run_tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare artifacts directory
        run: |
          mkdir -p artifacts

      - name: Train regression model
        run: |
          cd src
          python train.py

      - name: Quantize regression model
        run: |
          cd src
          python quantize.py

      - name: List model artifacts
        run: |
          echo "Artifacts in artifacts directory:"
          ls -la artifacts/
          echo "Current working directory:"
          pwd
          echo "All .joblib files found:"
          find . -name "*.joblib" -type f

      - name: Upload quantized model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quantized-artifacts
          path: |
            src/artifacts/
          retention-days: 30
          if-no-files-found: error

  docker_build_test:
    runs-on: ubuntu-latest
    name: Build and Validate Docker Image
    needs: model_train_quant

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare artifacts directory
        run: |
          mkdir -p artifacts

      - name: Download quantized model artifacts
        uses: actions/download-artifact@v4
        with:
          name: quantized-artifacts
          path: artifacts/

      - name: Validate downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -la artifacts/
          echo "Checking for required model files:"
          test -f artifacts/linear_regression_model.joblib && echo "Main model found" || echo "Main model missing"
          test -f artifacts/unquant_params.joblib && echo "Unquant params found" || echo "Unquant params missing"
          test -f artifacts/quant_params.joblib && echo "Quant params found" || echo "Quant params missing"

      - name: Build Docker image
        run: |
          docker build -t mlops-linear-regression .

      - name: Run Docker container for validation
        run: |
          docker run --rm mlops-linear-regression